from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np

from unmesh.ir import validate

from ..corpus import load_manifest, select
from ..groundtruth import generate
from ..labels import DEFLECTION_SETTINGS, LabeledMesh, tessellate
from ..oracle import build_oracle_ir
from .core import OPERATORS, apply, to_original_points

SEVERITIES = (0.0, 0.5, 1.0)
SEED = 20260101


def _closed(mesh: LabeledMesh) -> bool:
    import unmesh

    _, idx, *_ = unmesh.weld(mesh.tris, 0.0)
    directed: dict[tuple[int, int], int] = {}
    for a, b, c in idx.tolist():
        for e in ((a, b), (b, c), (c, a)):
            directed[e] = directed.get(e, 0) + 1
    return all(n == 1 for n in directed.values()) and all(
        (e[1], e[0]) in directed for e in directed
    )


def _ir_valid(mesh: LabeledMesh) -> bool:
    try:
        return validate(build_oracle_ir(mesh)) == []
    except Exception:
        return False


def smoke_meshes() -> list[LabeledMesh]:
    lin, ang = DEFLECTION_SETTINGS[0]
    return [
        tessellate(generate(e["family"], e["seed"]).solid, lin, ang)
        for e in select(load_manifest(), "smoke")
    ]


def stats(meshes: list[LabeledMesh], name: str, severity: float) -> dict[str, float | bool]:
    sq, peak, closed, valid = [], 0.0, True, True
    for mesh in meshes:
        out = apply(name, mesh, severity, SEED)
        back = to_original_points(out, out.tris.reshape(-1, 3)).reshape(-1, 3, 3)
        if (
            OPERATORS[name].changes_frame
            and np.linalg.det(np.array(out.metadata.get("to_original", np.eye(4).tolist()))[:3, :3])
            < 0
            and severity > 0
        ):
            back = back[:, [0, 2, 1]]
        d = np.linalg.norm(back - mesh.tris, axis=2).ravel()
        sq.append(d**2)
        peak = max(peak, float(d.max()))
        closed &= _closed(out)
        valid &= _ir_valid(out)
    return {
        "rms_um": 1000.0 * float(np.sqrt(np.concatenate(sq).mean())),
        "max_um": 1000.0 * peak,
        "closed": closed,
        "ir_valid": valid,
    }


def render(meshes: list[LabeledMesh] | None = None) -> str:
    meshes = meshes or smoke_meshes()
    lines = [
        "# Degradation operators",
        "",
        "Generated by `uv run python -m unmesh_harness.degrade.report`; do not edit by hand.",
        "",
        "An operator is a pure function `(LabeledMesh, severity in [0, 1], seed) -> LabeledMesh`, "
        "registered by name in `unmesh_harness.degrade.OPERATORS`. Severity 0 returns the input "
        "geometry bit-exactly. The result carries every label through: `face_id`, the face table, "
        'adjacency, edge polylines, vertices and shells. `metadata["history"]` records '
        "`(op, severity, seed, params)` for each step, with the physical parameters actually used. "
        '`metadata["to_original"]` is a 4x4 matrix taking degraded coordinates back to the '
        "original frame; pose operators update it, and `degrade.to_original_points` applies it. "
        "After a mirror the triangle winding was flipped to keep normals outward, so a point-wise "
        "comparison of triangle corners needs corners 1 and 2 swapped.",
        "",
        "Rules every operator follows:",
        "",
        "- Coordinates are transformed point-wise (or per distinct vertex for noise), so a vertex "
        "shared by several triangles, a vertex-table entry and an edge-polyline node that coincide "
        "before still coincide after, and a watertight mesh stays watertight.",
        "- Pose operators also transform the analytic parameters in the face table. Mirroring "
        "reflects origins, apexes, centres, normals and axes with the same matrix, keeps each "
        "face's `reversed` flag (the outward normal is a function of axis and position only), "
        "swaps triangle corners 1 and 2, and toggles `forward_in_a` on every adjacency because "
        "a reflection reverses the sense in which a face boundary is traversed.",
        "- Precision and noise operators leave the face table at the true analytic surfaces: "
        "that is the ground truth the mesh is supposed to recover.",
        "- The random stream is `numpy.random.default_rng(seed)`; vertices are visited in "
        "`np.unique` order, so output is bit-identical across processes.",
        "",
        "## Severity scale",
        "",
        "| operator | family | severity 0 | severity 1 |",
        "|---|---|---|---|",
    ]
    for op in OPERATORS.values():
        lines.append(f"| `{op.name}` | {op.family} | {op.severity_0} | {op.severity_1} |")
    lines += [
        "",
        "Noise amplitude is `severity * 50 um` (Gaussian standard deviation), stored as "
        "`sigma_mm_*` in the history params. `truncated_digits` uses `round(9 - 6 * severity)` "
        "significant digits; `inch_round_trip` uses `round(7 - 4 * severity)` inch decimals. "
        "Both can collapse short edges at high severity and so document that they do not "
        "guarantee watertightness there.",
        "",
        "## Displacement sheet",
        "",
        f"{len(meshes)} smoke-corpus parts, deflection {DEFLECTION_SETTINGS[0]}, seed {SEED}. "
        "Displacement is measured in the original frame, per triangle corner. `closed` is a "
        "closed manifold after an exact weld; `IR valid` is the oracle IR built from the degraded "
        "mesh passing `validate`.",
        "",
        "| operator | severity | rms (um) | max (um) | closed | IR valid |",
        "|---|---|---|---|---|---|",
    ]
    for name in OPERATORS:
        for severity in SEVERITIES:
            s = stats(meshes, name, severity)
            lines.append(
                f"| `{name}` | {severity} | {s['rms_um']:.3f} | {s['max_um']:.3f} | "
                f"{'yes' if s['closed'] else 'no'} | {'yes' if s['ir_valid'] else 'no'} |"
            )
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", default="docs/degradations.md")
    args = parser.parse_args()
    Path(args.out).write_text(render())


if __name__ == "__main__":
    main()
