from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np

from unmesh.ir import validate

from ..corpus import load_manifest, select
from ..groundtruth import generate
from ..labels import DEFLECTION_SETTINGS, LabeledMesh, tessellate
from ..oracle import build_oracle_ir
from .core import OPERATORS, apply, to_original, to_original_points

SEVERITIES = (0.0, 0.5, 1.0)
SEED = 20260101
REFINE_FOR_SHEET = 0.3


def _closed(mesh: LabeledMesh) -> bool:
    import unmesh

    _, idx, *_ = unmesh.weld(mesh.tris, 0.0)
    directed: dict[tuple[int, int], int] = {}
    for a, b, c in idx.tolist():
        for e in ((a, b), (b, c), (c, a)):
            directed[e] = directed.get(e, 0) + 1
    return all(n == 1 for n in directed.values()) and all(
        (e[1], e[0]) in directed for e in directed
    )


def _ir_valid(mesh: LabeledMesh) -> bool:
    try:
        return validate(build_oracle_ir(mesh)) == []
    except Exception:
        return False


def smoke_meshes() -> list[LabeledMesh]:
    lin, ang = DEFLECTION_SETTINGS[0]
    return [
        tessellate(generate(e["family"], e["seed"]).solid, lin, ang)
        for e in select(load_manifest(), "smoke")
    ]


Chain = tuple[tuple[str, float | None], ...]


def curved_meshes() -> list[LabeledMesh]:
    from build123d import Box, fillet

    return [tessellate(fillet(Box(20, 20, 20).edges(), 3), 0.05, 0.3)]


def run_chain(mesh: LabeledMesh, chain: Chain, severity: float) -> LabeledMesh:
    for name, fixed in chain:
        mesh = apply(name, mesh, severity if fixed is None else fixed, SEED)
    return mesh


def stats(meshes: list[LabeledMesh], chain: Chain, severity: float) -> dict[str, float | bool]:
    sq, peak, closed, valid, grown = [], 0.0, True, True, []
    for mesh in meshes:
        out = run_chain(mesh, chain, severity)
        back = to_original_points(out, out.tris.reshape(-1, 3)).reshape(-1, 3, 3)
        if np.linalg.det(to_original(out)[:3, :3]) < 0:
            back = back[:, [0, 2, 1]]
        refined = len(out.tris) != len(mesh.tris)
        if refined:
            base = run_chain(mesh, tuple(c for c in chain if c[0] == "refine"), severity)
            d = np.linalg.norm(back - base.tris, axis=2).ravel()
        else:
            d = np.linalg.norm(back - mesh.tris, axis=2).ravel()
        grown.append(len(out.tris) / len(mesh.tris))
        sq.append(d**2)
        peak = max(peak, float(d.max()))
        closed &= _closed(out)
        valid &= _ir_valid(out)
    return {
        "rms_um": 1000.0 * float(np.sqrt(np.concatenate(sq).mean())),
        "max_um": 1000.0 * peak,
        "closed": closed,
        "ir_valid": valid,
        "tris_ratio": float(np.mean(grown)),
    }


def render(meshes: list[LabeledMesh] | None = None) -> str:
    meshes = meshes or smoke_meshes()
    curved = curved_meshes()
    lines = [
        "# Degradation operators",
        "",
        "Generated by `uv run python -m unmesh_harness.degrade.report`; do not edit by hand.",
        "",
        "An operator is a pure function `(LabeledMesh, severity in [0, 1], seed) -> LabeledMesh`, "
        "registered by name in `unmesh_harness.degrade.OPERATORS`. Severity 0 returns the input "
        "geometry bit-exactly. The result carries every label through: `face_id`, the face table, "
        'adjacency, edge polylines, vertices and shells. `metadata["history"]` records '
        "`(op, severity, seed, params)` for each step, with the physical parameters actually used. "
        '`metadata["to_original"]` is a 4x4 matrix taking degraded coordinates back to the '
        "original frame; pose operators update it, and `degrade.to_original_points` applies it. "
        "After a mirror the triangle winding was flipped to keep normals outward, so a point-wise "
        "comparison of triangle corners needs corners 1 and 2 swapped.",
        "",
        "Rules every operator follows:",
        "",
        "- Coordinates are transformed point-wise (or per distinct vertex for noise), so a vertex "
        "shared by several triangles, a vertex-table entry and an edge-polyline node that coincide "
        "before still coincide after, and a watertight mesh stays watertight.",
        "- Pose operators also transform the analytic parameters in the face table. Mirroring "
        "reflects origins, apexes, centres, normals and axes with the same matrix, keeps each "
        "face's `reversed` flag (the outward normal is a function of axis and position only), "
        "swaps triangle corners 1 and 2, and toggles `forward_in_a` on every adjacency because "
        "a reflection reverses the sense in which a face boundary is traversed.",
        "- Precision and noise operators leave the face table at the true analytic surfaces: "
        "that is the ground truth the mesh is supposed to recover.",
        "- Truth edges and vertices: `adjacency[*].points` and `vertices` move with the mesh so "
        "the oracle IR of a degraded mesh stays self-consistent. The clean positions are kept "
        'unchanged in `metadata["truth"]` (`vertices`, `edge_points`, captured from the '
        "mesh as first passed to `apply`, in that mesh's frame) and no operator touches them; "
        "`to_original` maps degraded coordinates into that frame.",
        "- `refine` (tessellation family) bisects every edge longer than the target, with one "
        "midpoint per edge shared by both sides, so the mesh stays conforming and watertight. "
        "Midpoints on edges of non-planar faces are solved onto the analytic surface(s) of the "
        "incident faces (Gauss-Newton on the surfaces' implicit functions), and edge polylines "
        "gain the new boundary nodes. Planar faces have no interior vertices straight out of "
        "OCCT, so `noise_off_plane` raises `ValueError` unless the mesh was refined first.",
        "- The random stream is `numpy.random.default_rng(seed)`; vertices are visited in "
        "`np.unique` order, so output is bit-identical across processes.",
        "",
        "## Severity scale",
        "",
        "| operator | family | severity 0 | severity 1 |",
        "|---|---|---|---|",
    ]
    for op in OPERATORS.values():
        lines.append(f"| `{op.name}` | {op.family} | {op.severity_0} | {op.severity_1} |")
    lines += [
        "",
        "Noise amplitude A is `severity * 50 um` and is a hard bound: isotropic noise draws "
        "uniformly from a ball of radius A, the others a scalar uniformly from [-A, A] along "
        "their direction. Every noise history entry records `amplitude_mm`, `distribution` and "
        "the realised `max_displacement_mm`. `truncated_digits` uses `round(9 - 6 * severity)` "
        "significant digits; `inch_round_trip` uses `round(7 - 4 * severity)` inch decimals. "
        "Both can collapse short edges at high severity and so document that they do not "
        "guarantee watertightness there.",
        "",
        "## Displacement sheet",
        "",
        f"Seed {SEED}. Displacement is measured in the original frame, per triangle corner, "
        "against the undegraded mesh (against the refined mesh for chains that start with "
        "`refine`; `-` for `refine` alone, whose new vertices have no clean counterpart). "
        "`closed` is a closed manifold after an exact weld; `IR valid` is the oracle IR built "
        "from the degraded mesh passing `validate`. Binary operators are sampled at 0 and 1 "
        "only. `refine -> noise_off_plane` fixes refine at severity 0.3 (diagonal / 20) and "
        "sweeps the noise severity.",
        "",
        "| parts | operator | severity | rms (um) | max (um) | tris x | closed | IR valid |",
        "|---|---|---|---|---|---|---|---|",
    ]
    sets = [
        (f"smoke ({len(meshes)})", meshes, DEFLECTION_SETTINGS[0]),
        ("filleted box", curved, (0.05, 0.3)),
    ]
    for label, group, _ in sets:
        for name, op in OPERATORS.items():
            rows: list[tuple[str, Chain]] = [(f"`{name}`", ((name, None),))]
            if name == "noise_off_plane":
                rows = [
                    ("`refine -> noise_off_plane`", (("refine", REFINE_FOR_SHEET), (name, None)))
                ]
            for row_label, chain in rows:
                for severity in (0.0, 1.0) if op.binary else SEVERITIES:
                    s = stats(group, chain, severity)
                    ratio = s["tris_ratio"]
                    only_refine = name == "refine"
                    rms = "-" if only_refine else f"{s['rms_um']:.3f}"
                    peak = "-" if only_refine else f"{s['max_um']:.3f}"
                    lines.append(
                        f"| {label} | {row_label} | {severity} | {rms} | {peak} | {ratio:.1f} | "
                        f"{'yes' if s['closed'] else 'no'} | {'yes' if s['ir_valid'] else 'no'} |"
                    )
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", default="docs/degradations.md")
    args = parser.parse_args()
    Path(args.out).write_text(render())


if __name__ == "__main__":
    main()
