from __future__ import annotations

import argparse
import math
from collections import Counter
from pathlib import Path

import numpy as np

from unmesh.ir import validate

from ..corpus import load_manifest, select
from ..groundtruth import generate
from ..labels import DEFLECTION_SETTINGS, LabeledMesh, tessellate
from ..oracle import build_oracle_ir
from .core import OPERATORS, apply, chain, to_original, to_original_points
from .faults import DISPOSITION
from .presets import PRESETS
from .processing import POLYLINES_COINCIDE

SEVERITIES = (0.0, 0.5, 1.0)
SEED = 20260101
REFINE_FOR_SHEET = 0.3


def _closed(mesh: LabeledMesh) -> bool:
    import unmesh

    _, idx, *_ = unmesh.weld(mesh.tris, 0.0)
    directed: dict[tuple[int, int], int] = {}
    for a, b, c in idx.tolist():
        for e in ((a, b), (b, c), (c, a)):
            directed[e] = directed.get(e, 0) + 1
    return all(n == 1 for n in directed.values()) and all(
        (e[1], e[0]) in directed for e in directed
    )


def _ir_valid(mesh: LabeledMesh) -> bool:
    try:
        return validate(build_oracle_ir(mesh)) == []
    except Exception:
        return False


def smoke_meshes() -> list[LabeledMesh]:
    lin, ang = DEFLECTION_SETTINGS[0]
    return [
        tessellate(generate(e["family"], e["seed"]).solid, lin, ang)
        for e in select(load_manifest(), "smoke")
    ]


Chain = tuple[tuple[str, float | None], ...]


def curved_meshes() -> list[LabeledMesh]:
    from build123d import Box, fillet

    return [tessellate(fillet(Box(20, 20, 20).edges(), 3), 0.05, 0.3)]


def tess_meshes() -> list[tuple[str, LabeledMesh]]:
    from build123d import Cylinder

    cylinder = tessellate(Cylinder(5, 20), 0.05, 0.3)
    ngon = generate("ngon_prism", 3)
    lin, ang = ngon.parameters["pair_deflection"]
    ngon_mesh = tessellate(ngon.solid, lin, ang)
    fillet_gt = generate("one_segment_fillet", 0)
    flin, fang = DEFLECTION_SETTINGS[0]
    return [
        ("cylinder", cylinder),
        ("ngon", ngon_mesh),
        ("fillet", tessellate(fillet_gt.solid, flin, fang)),
    ]


def tess_stats(mesh: LabeledMesh) -> dict[str, float]:
    import unmesh

    edges = set()
    for tri in mesh.tris:
        for i in range(3):
            a, b = tuple(tri[i]), tuple(tri[(i + 1) % 3])
            edges.add((min(a, b), max(a, b)))
    chords = np.array([math.dist(a, b) for a, b in edges])
    a = np.linalg.norm(mesh.tris[:, 1] - mesh.tris[:, 0], axis=1)
    b = np.linalg.norm(mesh.tris[:, 2] - mesh.tris[:, 1], axis=1)
    c = np.linalg.norm(mesh.tris[:, 0] - mesh.tris[:, 2], axis=1)
    s = (a + b + c) / 2
    area = np.sqrt(np.maximum(s * (s - a) * (s - b) * (s - c), 1e-30))
    aspect = np.maximum(a, np.maximum(b, c)) ** 2 / (2 * area)
    _, idx, *_ = unmesh.weld(mesh.tris, 0.0)
    valence = np.array(sorted(Counter(idx.ravel().tolist()).values()), dtype=float)
    return {
        "tris": len(mesh.tris),
        "chord_mean": float(chords.mean()),
        "chord_std": float(chords.std()),
        "aspect_mean": float(aspect.mean()),
        "aspect_p99": float(np.percentile(aspect, 99)),
        "valence_mean": float(valence.mean()),
        "valence_max": float(valence.max()),
    }


def run_chain(mesh: LabeledMesh, spec: Chain, severity: float) -> LabeledMesh:
    steps = [(name, severity if fixed is None else fixed) for name, fixed in spec]
    return chain(mesh, steps, SEED)


def stats(meshes: list[LabeledMesh], spec: Chain, severity: float) -> dict[str, float | bool]:
    sq, peak, closed, valid, grown = [], 0.0, True, True, []
    counts_change = OPERATORS[spec[-1][0]].family in ("tessellation", "processing")
    for mesh in meshes:
        out = run_chain(mesh, spec, severity)
        back = to_original_points(out, out.tris.reshape(-1, 3)).reshape(-1, 3, 3)
        if np.linalg.det(to_original(out)[:3, :3]) < 0:
            back = back[:, [0, 2, 1]]
        if not counts_change:
            base = run_chain(mesh, tuple(c for c in spec if c[0] == "refine"), severity)
            if len(back) == len(base.tris):
                d = np.linalg.norm(back - base.tris, axis=2).ravel()
                sq.append(d**2)
                peak = max(peak, float(d.max()))
        grown.append(len(out.tris) / len(mesh.tris))
        closed &= _closed(out)
        valid &= _ir_valid(out)
    return {
        "rms_um": 1000.0 * float(np.sqrt(np.concatenate(sq).mean())) if sq else None,
        "max_um": 1000.0 * peak if sq else None,
        "closed": closed,
        "ir_valid": valid,
        "tris_ratio": float(np.mean(grown)),
    }


def render(meshes: list[LabeledMesh] | None = None) -> str:
    meshes = meshes or smoke_meshes()
    curved = curved_meshes()
    lines = [
        "# Degradation operators",
        "",
        "Generated by `uv run python -m unmesh_harness.degrade.report`; do not edit by hand.",
        "",
        "An operator is a pure function `(LabeledMesh, severity in [0, 1], seed) -> LabeledMesh`, "
        "registered by name in `unmesh_harness.degrade.OPERATORS`. Severity 0 returns the input "
        "geometry bit-exactly. The result carries every label through: `face_id`, the face table, "
        'adjacency, edge polylines, vertices and shells. `metadata["history"]` records '
        "`(op, severity, seed, params)` for each step, with the physical parameters actually used. "
        '`metadata["to_original"]` is a 4x4 matrix taking degraded coordinates back to the '
        "original frame; pose operators update it, and `degrade.to_original_points` applies it. "
        "After a mirror the triangle winding was flipped to keep normals outward, so a point-wise "
        "comparison of triangle corners needs corners 1 and 2 swapped.",
        "",
        "Rules every operator follows:",
        "",
        "- Coordinates are transformed point-wise (or per distinct vertex for noise), so a vertex "
        "shared by several triangles, a vertex-table entry and an edge-polyline node that coincide "
        "before still coincide after, and a watertight mesh stays watertight.",
        "- Pose operators also transform the analytic parameters in the face table. Mirroring "
        "reflects origins, apexes, centres, normals and axes with the same matrix, keeps each "
        "face's `reversed` flag (the outward normal is a function of axis and position only), "
        "swaps triangle corners 1 and 2, and toggles `forward_in_a` on every adjacency because "
        "a reflection reverses the sense in which a face boundary is traversed.",
        "- Precision and noise operators leave the face table at the true analytic surfaces: "
        "that is the ground truth the mesh is supposed to recover.",
        "- Truth edges and vertices: `adjacency[*].points` and `vertices` move with the mesh so "
        "the oracle IR of a degraded mesh stays self-consistent. The clean positions are kept "
        'unchanged in `metadata["truth"]` (`vertices`, `edge_points`, captured from the '
        "mesh as first passed to `apply`, in that mesh's frame) and no operator touches them; "
        "`to_original` maps degraded coordinates into that frame.",
        "- `refine` (tessellation family) bisects every edge longer than the target, with one "
        "midpoint per edge shared by both sides, so the mesh stays conforming and watertight. "
        "Midpoints on edges of non-planar faces are solved onto the analytic surface(s) of the "
        "incident faces (Gauss-Newton on the surfaces' implicit functions), and edge polylines "
        "gain the new boundary nodes. Planar faces have no interior vertices straight out of "
        "OCCT, so `noise_off_plane` raises `ValueError` unless the mesh was refined first; "
        "meshes with no planar face at all are skipped unchanged.",
        "- The random stream is `numpy.random.default_rng(seed)`; vertices are visited in "
        "`np.unique` order, so output is bit-identical across processes.",
        "- `coarsen` collapses shortest edges first into the surviving endpoint (CAD vertices "
        "never merge, the link condition keeps the mesh a closed manifold, no face loses its "
        "last triangle, b collapses into a only if faces(b) is a subset of faces(a), an edge-"
        "polyline node only into an adjacent node of the same polyline, and no collapse may "
        "fold a triangle or create a zero-area one), so surviving curved nodes stay exactly "
        "on the analytic surface.",
        "- `retriangulate` reuses boundary vertices bit-exactly and only touches planar faces "
        "without interior vertices; curved faces are skipped.",
        "- `nonuniform_chords` moves only vertices on one or two faces along the surface or the "
        "shared edge (up to 45% of the shorter neighbouring segment), reprojects them onto "
        "the incident analytic surfaces, rejects moves that flip a triangle, and leaves CAD "
        "corners fixed.",
        "- `slivers` splits edges on both sides at once (conforming, watertight) and never "
        "splits edges of degenerate input triangles, and rejects split points whose projection "
        "onto the surface flips a triangle; `t_junctions` splits one side only and so "
        "is not watertight by design, while face ids and polylines stay aligned in both. "
        "`t_junctions` intentionally leaves edge polylines that are not mesh edges on both sides.",
        "- `fillet_rows` rebuilds cylinder fillet strips with an explicit segment count on the "
        "exact analytic arc, triangulating each strip row-band and the affected planar "
        "neighbours with the seed-independent canonical triangulation; strips whose "
        "tangent-line stations differ, and anything else ineligible, is recorded as skipped "
        "and left untouched.",
        "",
        "- `defect`-family operators intentionally break the mesh (open seams, holes, extra "
        "shells, duplicated or reversed triangles). Triangles copied from the mesh keep their "
        "source `face_id`; brand-new synthetic triangles (stray shells and fin triangles) get "
        "`face_id` -1 (unknown face), which the oracle excludes from every region. Operators "
        "that change the triangle count report no displacement.",
        "",
        "- `processing`-family operators (decimation, remeshing, smoothing, vertex "
        "clustering) rebuild or move the triangulation the way mesh-processing "
        "pipelines do. Topology-changing operators relabel every output triangle "
        "from the clean labeled source mesh: source triangles are densely sampled "
        "(barycentric lattice at bbox-diagonal / 400 plus the centroid), a "
        "cKDTree over the samples proposes candidate source triangles for the "
        "output triangle's centroid and 3 edge midpoints (midpoints pulled 10% "
        "toward the centroid, off exact shared edges), each probe votes its "
        "exactly containing triangle or else its nearest-sample majority, and the "
        "triangle takes the 4-probe majority with `label_confidence` the agreeing "
        "fraction. Coplanar faces sharing one surface keep their trimmed labels. "
        "Metrics that score per-triangle labels mask triangles below 0.9 "
        "confidence. The face table, adjacency, vertices and shells stay the "
        "clean truth, except the smoothing operators move shared vertices so "
        "their edge polylines move with the mesh. Smoothing keeps connectivity, "
        "so it keeps the original labels exactly at confidence 1.0 with the "
        "displacement capped to severity * 1% of the bbox diagonal. Quadric "
        "decimation targets keep ratio 1 - 0.9 * severity with a 4-triangle "
        "floor. Watertightness is per operator: smoothing and isotropic "
        "remeshing preserve it, quadric decimation and vertex clustering do not.",
        "",
        "## Defect disposition",
        "",
        "Whether the converter is expected to REPAIR a defect (same analytic IR as the clean "
        "mesh, plus a warning) or REPORT it (open/non-manifold facets shell, plus a warning):",
        "",
        *[f"- `{name}`: {text}" for name, text in DISPOSITION.items()],
        "",
        "## Severity scale",
        "",
        "| operator | family | severity 0 | severity 1 |",
        "|---|---|---|---|",
    ]
    for op in OPERATORS.values():
        lines.append(f"| `{op.name}` | {op.family} | {op.severity_0} | {op.severity_1} |")
    lines += [
        "",
        "Noise amplitude A is `severity * 50 um` and is a hard bound: isotropic noise draws "
        "uniformly from a ball of radius A, the others a scalar uniformly from [-A, A] along "
        "their direction. Every noise history entry records `amplitude_mm`, `distribution` and "
        "the realised `max_displacement_mm`. `truncated_digits` uses `round(9 - 6 * severity)` "
        "significant digits; `inch_round_trip` uses `round(7 - 4 * severity)` inch decimals. "
        "Both can collapse short edges at high severity and so document that they do not "
        "guarantee watertightness there.",
        "",
        "## Presets",
        "",
        "Named toolchain presets compose the operators above into degradation chains applied "
        "with `degrade.chain`, which runs step `i` as `apply(name, mesh, severity, seed + i)`. "
        "Each preset is a fixed list of `(operator, severity)` steps built only from registered "
        'operators; a grid cell names one with `"preset"` instead of spelling out `"steps"`.',
        "",
        "| preset | steps | imitates |",
        "|---|---|---|",
        *[
            f"| `{p.name}` | "
            + ", ".join(f"`{op}` at {severity}" for op, severity in p.steps)
            + f" | {p.rationale} |"
            for p in PRESETS.values()
        ],
        "",
        "Quantitative comparison of each preset's mesh statistics against real exports from "
        "the tool it imitates waits for #29.",
        "",
        "## Displacement sheet",
        "",
        f"Seed {SEED}. Displacement is measured in the original frame, per triangle corner, "
        "against the undegraded mesh (against the refined mesh for chains that start with "
        "`refine`; `-` for the tessellation family and the topology-changing processing "
        "operators, whose triangle counts "
        "or corner correspondences change - see Tessellation statistics below). "
        "`closed` is a closed manifold after an exact weld; `IR valid` is the oracle IR built "
        "from the degraded mesh passing `validate`. Binary operators are sampled at 0 and 1 "
        "only. `refine -> noise_off_plane` fixes refine at severity 0.3 (diagonal / 20) and "
        "sweeps the noise severity. Meshes without a planar face skip `noise_off_plane` "
        'with history params `{"skipped": "no planar faces"}`.',
        "",
        "| parts | operator | severity | rms (um) | max (um) | tris x | closed | IR valid |",
        "|---|---|---|---|---|---|---|---|",
    ]
    sets = [
        ("smoke", meshes, DEFLECTION_SETTINGS[0]),
        ("filleted box", curved, (0.05, 0.3)),
    ]
    for base, group, _ in sets:
        for name, op in OPERATORS.items():
            rows: list[tuple[str, Chain]] = [(f"`{name}`", ((name, None),))]
            if name == "noise_off_plane":
                rows = [
                    ("`refine -> noise_off_plane`", (("refine", REFINE_FOR_SHEET), (name, None)))
                ]
            for row_label, spec in rows:
                use = group
                label = f"smoke ({len(use)})" if base == "smoke" else base
                for severity in (0.0, 1.0) if op.binary else SEVERITIES:
                    s = stats(use, spec, severity)
                    ratio = s["tris_ratio"]
                    counts_change = op.family in ("tessellation", "processing")
                    counts_change = counts_change and name not in POLYLINES_COINCIDE
                    rms = "-" if counts_change or s["rms_um"] is None else f"{s['rms_um']:.3f}"
                    peak = "-" if counts_change or s["max_um"] is None else f"{s['max_um']:.3f}"
                    lines.append(
                        f"| {label} | {row_label} | {severity} | {rms} | {peak} | {ratio:.1f} | "
                        f"{'yes' if s['closed'] else 'no'} | {'yes' if s['ir_valid'] else 'no'} |"
                    )
    lines += [
        "",
        "## Tessellation statistics",
        "",
        f"Seed {SEED}. Chord length is over unique mesh edges; aspect ratio is Lmax^2 / (2A) "
        "per triangle (1.15 for equilateral); valence is the incident-triangle count per "
        "welded vertex. Baseline rows (`-` operator) are the undegraded OCCT meshes. Every "
        "variant shifts at least one of these distributions against OCCT's default.",
        "",
        "| mesh | operator | severity | tris | chord mean (mm) | chord std | aspect mean | "
        "aspect p99 | valence mean | valence max |",
        "|---|---|---|---|---|---|---|---|---|---|",
    ]
    for label, mesh in tess_meshes():
        t = tess_stats(mesh)
        lines.append(
            f"| {label} | `-` | - | {t['tris']} | {t['chord_mean']:.4f} | {t['chord_std']:.4f} | "
            f"{t['aspect_mean']:.3f} | {t['aspect_p99']:.3f} | {t['valence_mean']:.3f} | "
            f"{t['valence_max']:.0f} |"
        )
        for name, op in OPERATORS.items():
            if op.family != "tessellation" or name == "refine":
                continue
            for severity in (0.5, 1.0):
                out = apply(name, mesh, severity, SEED)
                t = tess_stats(out)
                lines.append(
                    f"| {label} | `{name}` | {severity} | {t['tris']} | "
                    f"{t['chord_mean']:.4f} | {t['chord_std']:.4f} | {t['aspect_mean']:.3f} | "
                    f"{t['aspect_p99']:.3f} | {t['valence_mean']:.3f} | {t['valence_max']:.0f} |"
                )
    lines += [
        "",
        "## Processing statistics",
        "",
        f"Seed {SEED}. Per-operator stats over the same meshes as above, plus one "
        "aggregate row per operator over the full smoke set. `conf<0.9` is the "
        "fraction of output triangles whose `label_confidence` is below 0.9; metrics that "
        "score per-triangle labels mask those triangles. `faces lost` counts clean faces "
        "with no output triangle at confidence 0.9 or above. `closed` and `IR valid` "
        "are as in the displacement sheet.",
        "",
        "| mesh | operator | severity | tris | closed | IR valid | conf mean | conf<0.9 | "
        "faces lost |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    smoke = smoke_meshes()
    for label, mesh in tess_meshes():
        lines.append(f"| {label} | `-` | - | {len(mesh.tris)} | yes | yes | 1.000 | 0.000 | 0 |")
        for name, op in OPERATORS.items():
            if op.family != "processing":
                continue
            for severity in (0.5, 1.0):
                out = apply(name, mesh, severity, SEED)
                lines.append(_processing_row(label, f"`{name}`", severity, mesh, out))
    for name, op in OPERATORS.items():
        if op.family != "processing":
            continue
        for severity in (0.5, 1.0):
            tris = lost = below = total = 0
            weighted = 0.0
            closed = valid = True
            for mesh in smoke:
                out = apply(name, mesh, severity, SEED)
                conf = np.array(out.metadata.get("label_confidence", [1.0]))
                tris += len(out.tris)
                lost += _faces_lost(mesh, out)
                below += int((conf < 0.9).sum())
                weighted += float(conf.sum())
                total += len(conf)
                closed &= _closed(out)
                valid &= _ir_valid(out)
            lines.append(
                f"| smoke ({len(smoke)}) | `{name}` | {severity} | {tris} | "
                f"{'yes' if closed else 'no'} | {'yes' if valid else 'no'} | "
                f"{weighted / total:.3f} | {below / total:.3f} | {lost} |"
            )
    return "\n".join(lines) + "\n"


def _faces_lost(clean: LabeledMesh, out: LabeledMesh) -> int:
    conf = np.array(out.metadata.get("label_confidence", np.ones(len(out.tris))))
    keep = np.asarray(out.face_id)[np.asarray(conf) >= 0.9]
    return sum(1 for f in clean.faces if not (keep == f.id).any())


def _processing_row(
    label: str, op: str, severity: float, clean: LabeledMesh, out: LabeledMesh
) -> str:
    conf = np.array(out.metadata.get("label_confidence", [1.0]))
    return (
        f"| {label} | {op} | {severity} | {len(out.tris)} | "
        f"{'yes' if _closed(out) else 'no'} | "
        f"{'yes' if _ir_valid(out) else 'no'} | {float(conf.mean()):.3f} | "
        f"{float((conf < 0.9).mean()):.3f} | {_faces_lost(clean, out)} |"
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", default="docs/degradations.md")
    args = parser.parse_args()
    Path(args.out).write_text(render())


if __name__ == "__main__":
    main()
